### ISSUE TITLE
nhymxu-at-coupon.php on line 19

### ISSUE THREAD

**Issue by tuanxuong** [interspace-vn/accesstrade-coupon#8]
Xin chào,
Mình bị lỗi
Parse error: syntax error, unexpected '[' in .../public_html/wp-content/plugins/nhymxu-at-coupon/nhymxu-at-coupon.php on line 19
khi kích hoạt plugin.
Mong được hỗ trợ

**Comment by nhymxu** [comment]
cái này do phiên bản PHP của bạn đang chạy dưới 5.4 nhé
Bạn cần đổi phiên bản PHP trong cpanel lên phiên bản từ 5.4 trở lên
